config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root to: 'application#index'

  resources :moss_matches, only: [:index, :show]
  resources :jplag_matches, only: [:show]

  resource :users, only: [] do
    get :autocomplete_display_name, :on => :collection
  end

  resources :groups do
    get :results
    get :statistics
    get :autocomplete_title, :on => :collection
    resources :groups, only: [:new]
    resources :accesses, only: [:index]
    resources :submission_tasks, only: [:new]
    resources :input_output_tasks, only: [:new]
    resources :jshell_tasks, only: [:new]
  end

  scope :groups do
    resources :attachments, only: [:create, :show]
  end

  resources :accesses, only: [:create]

  resources :accesses, only: [:destroy]

  resources :submission_tasks, except: [:new, :index] do
    get :results
    get :statistics
    get :moss_graph
    get :moss_results
    get :jplag_results
    get :download_tests
    get :download_submissions
    get :run_moss, to: 'moss_matches#run_moss'
    get :run_jplag, to: 'jplag_matches#run_jplag'
    resources :submissions, only: [:new]
  end

  resources :input_output_tasks, except: [:new, :index] do
    get :results
    get :statistics
    get :download_submissions
    resources :submissions, only: [:new]
  end

  resources :jshell_tasks, except: [:new, :index] do
    get :results
    get :statistics
    get :download_submissions
    resources :submissions, only: [:new]
  end

  resources :submissions, except: [:new] do
    get :download
    resources :feedbacks, only: [:new,:edit,:show, :update, :create]
  end

  resources :inputs, only: [:show]

  post '/lock_task', to: 'task_lock#toggle'
  post '/correct_task', to: 'task_lock#toggle_corrected'

  post 'submissions/batch_upload', to: 'submissions#batch_upload', as: 'submission_batch_upload'

  get 'errors/file_too_large'

  get 'doc', to: 'documentation#index'
  #get 'doc/*file', to: 'documentation#show'

  mount JavaSubmissionTester::Engine, at: 'java_tester'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end

app/models/task.rb
# coding: utf-8
class Task < Group
  mount_uploader :test, SubmissionTestUploader
  mount_uploader :hidden_test, SubmissionTestUploader
  mount_uploader :stub, SubmissionTestUploader

  has_many :submissions, dependent: :destroy
  has_many :test_suits, dependent: :destroy
  has_many :test_cases, :through => :test_suits
  has_many :test_results, :through => :submissions
  has_many :feedbacks, dependent: :destroy

  belongs_to :user

  #check that AT LEAST ONE of [test,hidden_test] is available
  validates_presence_of :test, if: proc{|obj| obj.hidden_test.current_path.nil?}
  validates_presence_of :hidden_test, if: proc{|obj| obj.test.current_path.nil?}

  validates :parent_id, presence: true
  validate :check_test_structure

  after_initialize :set_deadline_default

  before_save :create_test_structure_records, if: Proc.new { |o| o.new_record? || o.test_changed? || o.hidden_test_changed? || o.stub_changed? }
  after_commit :revalidate_and_rerun_tests, on: [:update]

  def test_jar_list
    return [self.test,self.hidden_test].select { |uploader| not uploader.current_path.nil? }
  end

  #either :test or :hidden_test ; one of them is available because of the validation
  def available_test
    return (self.hidden_test.current_path.nil?) ? self.test : self.hidden_test
  end

  def has_donwloadable_tests?
    not self.test.current_path.nil?
  end

  def test_runner
    raise 'Not Implemented!'
  end

  def has_submissions?(ability)
    Submission.accessible_by(ability).where(task_id: self.id).any?
  end

  def correct_wrong_data(ability)
    correct = correct_count(ability)
    wrong = wrong_count(ability)

    return {
        'korrekt' => correct,
        'falsch' => wrong
    }
  end

  def exception_count_data(ability)
    self.test_results.accessible_by(ability, :index).where.not(failure_exception: nil).group(:failure_exception).count
  end

  def wrong_count_data(ability)
    self.test_results.wrong.accessible_by(ability, :index).joins(:test_case).group('"test_cases"."name"').count
  end

  def average_result(ability, user=nil)
    correct = correct_count ability, user

    count_query = self.test_results.accessible_by(ability, :index)
    count_query = count_query.where(submission: Submission.where(user: user)) unless user.nil?
    count = count_query.count
    return if count == 0

    return correct.to_f / count * 100
  end

  def allow_subgroup?
    false
  end

  def allow_subtask?
    false
  end

  private

  def correct_count(ability, user=nil)
    correct_query = self.test_results.correct.accessible_by(ability, :index)
    correct_query = correct_query.where(submission: Submission.where(user: user)) unless user.nil?

    return correct_query.count
  end

  def wrong_count(ability, user=nil)
    wrong_query = self.test_results.wrong.accessible_by(ability, :index)
    wrong_query = wrong_query.where(submission: Submission.where(user: user)) unless user.nil?

    return wrong_query.count
  end

  def create_test_structure_records
    test_runner = self.test_runner
    no_test_cases = true

    begin
      Task.transaction do
        self.test_suits.destroy_all

        test_suit_names = test_runner.test_suit_names_for(test_jar_list, self.stub)
        test_suit_names.each do |test_suit_name|
          test_cases = test_runner.test_cases_for_testsuit(test_jar_list, self.stub, test_suit_name)

          if test_cases.any?
            no_test_cases = false

            test_suit = TestSuit.new
            test_suit.name = test_suit_name
            self.test_suits << test_suit

            test_cases.each do |test_case_name, values|
              test_case = TestCase.new
              test_case.name = test_case_name
              test_case.points = values['points']
              # test_case.extras = values['extras'] # for future
              test_suit.test_cases << test_case
            end
          end
        end

        if no_test_cases
          raise 'Es konnten keine Testfälle gefunden werden!'
        end
      end
    rescue => e
      self.errors.add :test, e.to_s
      throw(:abort)
    end
  end

  def check_test_structure
    return if self.errors.any?

    error = nil
    details = nil

    begin
      validation_result = self.test_runner.validate_test_structure available_test, self.stub
      error, details = validation_result[:error] unless validation_result.nil?
    rescue => e
      logger.warn "#{e}\n#{e.backtrace.join("\n")}"
      error = 'Test ist Fehlerhaft! Überprüfung der Teststruktur wurde mit Fehler beendet!'
    end
    self.errors.add(:test, error) unless error.nil?
    self.errors.add(:details, details) unless details.nil?
  end

  def revalidate_and_rerun_tests
    RerunTestJob.perform_later self.id
  end

  def set_deadline_default
    self.deadline = Time.now + 7.days if self.deadline.nil?
  end
end

app/controllers/tasks_controller.rb
# coding: utf-8
class TasksController < SecureController
  include ZipSubmissions
  include CSVResults

  before_action :set_task
  before_action :set_file_name_attributes

  def edit
    @group = @task
  end

  def create
    @task.user = @task.parent.user

    if @task.save
      flash[:notice] = 'Aufgabe erfolgreich erstellt'

      redirect_to @task
    else
      flash[:error] = 'Konnte Aufgabe nicht speichern'
      @group = @task
      render :new
    end
  end

  def update
    if @task.update_attributes task_params
      flash[:notice] = 'Aufgabe erfolgreich aktualisiert'

      redirect_to @task
    else
      @group = @task
      render :edit
    end
  end

  def destroy
    authorize! :destroy, @task
    @parent = @task.parent
    @task.destroy

    flash[:notice] = "#{@task.title} erfolgreich gelöscht!"

    if @parent.nil?
      redirect_to root_path
    else
      redirect_to polymorphic_path @parent
    end
  end

  def results
    @task = Task.includes(:submissions, :test_cases, :test_results).accessible_by(current_ability, :index).find_by! id: params[:task_id]
    @group = @task
    @submissions = @task.submissions.accessible_by(current_ability, :index).includes(:user).order('users.display_name ASC')
    @submission = @submissions.first if @submissions.count == 1
    @test_cases = @task.test_cases.accessible_by(current_ability, :index)

    if cannot? :statistics, @task
      @test_results = @submission.test_results unless @submission.nil?
      @unfinished = @test_results.count < @test_cases.count unless @test_results.nil?
    end


    if cannot?(:statistics, @task) and @submission.nil?
      flash[:alert] = 'Sie müssen eine Abgabe machen, bevor sie Ergebnisse einsehen können!'

      redirect_to @task
    else
      respond_to do |format|
        format.html
        format.csv { send_data csv_results_task(@submissions, @test_cases), filename: "#{@task.title}_results.csv" }
      end
    end
  end

  def download_submissions
    @task = Task.find_by! id: params[:task_id]

    authorize! :download, @task

    Tempfile.open do |f|
      f.close
      submissions = @task.submissions

      if params[:not_corrected] == "true"
        submissions = @task.submissions.reject { |s| s.user.has_locked_task?(@task) }
      end

      zip_submissions submissions, f.path

      send_file f.path, filename: "#{@task.title[0..20]}.zip"
    end
  end

  def statistics
    @task = Task.find_by! id: params[:task_id]
    @group = @task
    authorize! :statistics, @task

    @submissions = @task.submissions
  end

  def set_task
    raise 'set_task of TasksController not implemented!'
  end

  def task_params
    raise 'I need an implementaion *read with creepy voice*'
  end

  def set_file_name_attributes
    return if @task.nil?

    @test_file = @task.test.current_path unless @task.test.nil?
    @test_file = @task.test_cache unless @task.test_cache.nil?
    @test_file = File.basename @test_file unless @test_file.nil?

    @hidden_test = @task.hidden_test.current_path unless @task.hidden_test.nil?
    @hidden_test = @task.hidden_test_cache unless @task.hidden_test_cache.nil?
    @hidden_test = File.basename @hidden_test unless @hidden_test.nil?

    @stub_file = @task.stub.current_path unless @task.stub.nil?
    @stub_file = @task.stub_cache unless @task.stub_cache.nil?
    @stub_file = File.basename @stub_file unless @stub_file.nil?
  end

end

app/helpers/tasks_helper.rb
module TasksHelper

  def map_languages_to_select_options_with_help_path(tester_languages, current_selection)
    select_options = tester_languages.supported_language_names.map do |language_name|
      [language_name, {'data-path'.to_sym => tester_languages.runner_for_language(language_name).new.teacher_help_path }]
    end

    options_for_select(select_options, current_selection)
  end

  def table_result_class(submission, task)
    klass = submission.user.has_locked_task?(@task) ? 'result-locked' : 'result-unlocked'

    lock = TaskLock.find_by(user_id: submission.user.id, task_id: task.id)
    unless lock.nil?
      if lock.corrected?
        klass = 'result-corrected'
      end
    end

    klass
  end
end

app/views/tasks/_form.html.slim
.col-xs-12.col-md-10
  = bootstrap_form_for model, layout: :horizontal do |f|
    = f.hidden_field :parent_id
    = f.text_field :title
    = f.text_area :text_content, { 'data-provide' => 'markdown', 'data-resize' => 'true', 'data-iconlibrary' => 'fa', 'data-hidden-buttons' => 'cmdImage', 'data-footer' => render(partial: 'groups/text_area_footer', locals: {group: @group, form: f})}
    = f.datetime_select :deadline
    = f.form_group
      = f.check_box :visible
    = f.form_group
      = f.check_box :bonus

    = f.select :language, language_selection, {label: 'Programmiersprache'}, onchange: "updateHelpPath()"

    - unless @test_file.nil?
      = f.form_group label: {text: 'Aktueller Test'}
        = text_field_tag '', @test_file, readonly: true, class: 'form-control'
    = f.file_field :test, label: 'Test'
    = f.hidden_field :test_cache

    - unless @hidden_test.nil?
      = f.form_group label: {text: 'Aktueller Hidden Test'}
        = text_field_tag '', @hidden_test, readonly: true, class: 'form-control'
    = f.file_field :hidden_test, label: 'Hidden Test', help: "Hidden Tests sind optional."
    = f.hidden_field :hidden_test_cache


    = yield f

    - if f.object.errors[:details].any?
      = f.form_group
        = btn_link_to 'Details', '#details', class: 'btn-danger', data: {toggle: 'collapse'}
      #details.collapse
        pre = f.object.errors[:details].join(', ')

    = f.form_group
      => f.submit 'Aufgabe erstellen'
      => btn_link_to "Hilfe", "#", class: 'btn-info', target: '_blank', id: "help_btn"

javascript:
    updateHelpPath()

    function updateHelpPath() {
      var path = $("#submission_task_language option:selected").data("path")
      $("#help_btn").attr("href", path)
  }

app/views/tasks/_warnings_dialog.html.slim
- submission = locals[:submission]
.modal#submissionWarningDialog aria-hidden="false" aria-labelledby="submissionWarningDialog" role="dialog" tabindex="-1"
  .modal-dialog role="document" style="width: 85%;"
    .modal-content
      .modal-header
        button.close aria-label="Close" data-dismiss="modal" type="button"
          span aria-hidden="true"  &times;
        h4.modal-title
          = icon 'exclamation-circle '
          |   Warnungen zur Abgabe
      .modal-body.tab-content
        pre = submission.warning_text
      .modal-footer
        button.btn.btn-secondary data-dismiss="modal" type="button" style="width: 100%"  Schließen

javascript:
  $('.modal#submissionWarningDialog').modal({show: true})

app/views/tasks/results.html.slim
= render partial: 'breadcrumb', locals: { path_append: 'Ergebnisse' }

- if @submission&.warning_text && !@submission.warning_text.blank?
  = render 'warnings_dialog', locals: {submission: @submission}

= content_for :title
  = "Ergebnisse"

= content_for :main
  - if can? :statistics, @task
    .row
      h2.text-center
        = @task.title
        br
        small = "#{@task.submissions.count} Abgaben"
  .col-lg-3
    h4 Richtige vs Falsche
    = pie_chart @task.correct_wrong_data(current_ability), library: {backgroundColor: 'transparent'}
  .col-lg-3
    h4 Häufigkeit der Exceptions
    = pie_chart @task.exception_count_data(current_ability), library: {backgroundColor: 'transparent'}
  - if can? :statistics, @task
    .col-lg-3
      h4 Fehler / Test
      = pie_chart @task.wrong_count_data(current_ability), library: {backgroundColor: 'transparent'}
  - else
    h4.text-center Rankings
    br
    .col-lg-3
      .well.well-sm.text-center
        p.bold
          | besser als
        p
          = number_to_percentage(@submission.percent_rank, precision: 0)
    .col-lg-3
      .well.well-sm.text-center
        p
          | schneller als
        p
          | TODO
    .col-lg-3
      .well.well-sm.text-center
        p
          | code größe
        p
          | TODO
    .col-lg-3
      .well.well-sm.text-center
        p
          | Placeholder
        p
          | TODO

- if can? :statistics, @task
  div.alert.alert-danger.alert-dismissable
    Die Seite lädt sich selbst nicht neu. Bitte selber neuladen, falls Abgaben noch nicht verarbeitet wurden.

.col-lg-12
  table.table.table-striped.table-condensed
    thead
      tr
        th.first-column.word-wrap
          - if can? :download, @task
            .btn-group
              button.btn.btn-primary.dropdown-toggle[data-toggle='dropdown']
                ' Nutzer
                span.caret
              ul.dropdown-menu
                li = link_to 'Abgaben', polymorphic_url([@task, :download_submissions])
                li = link_to 'Abgaben (unkorrigiert)', polymorphic_url([@task, :download_submissions], not_corrected: true)
                li = link_to 'CSV', polymorphic_url([@task, :results], format: :csv)
          - else
            ' Nutzer

        th.text-center
          | Actions

        - @test_cases.each do |test_case|
          th.text-center
            = test_case.name
    tbody
      - @submissions.each do |submission|
        tr[class=(table_result_class(submission, @task))]
          td[class=(is_tutor(@task, submission.user) ? 'tutor' : 'student')]
            = link_to submission.display_name, submission_download_path(submission)
          td.btn-group
            - feedback = @task.feedbacks.find_by(student: submission.user)
            - if can? :feedback, submission and !feedback
              = link_to new_submission_feedback_path(submission), class: 'btn btn-outline-primary btn-sm'
                i.fa.fa-pencil
            - elsif can? :feedback, submission and feedback
              = link_to edit_submission_feedback_path(submission, feedback), class: 'btn btn-outline-primary btn-sm', "data-toggle" => "tooltip", "data-placement" => "bottom", "title" => "Create/Edit feedback"
                i.fa.fa-pencil
            - if can? :feedback, submission
              = link_to "", class: "btn btn-outline-success open-feedback-btn #{feedback.nil? ? '' : 'has-feedback'}", id: "feedback-btn-#{submission.id}", "data-toggle" => "tooltip", "data-placement" => "bottom", "data-feedback-id" => (feedback.nil? ? nil : feedback.id), "data-submission-id" => submission.id, "title" => (feedback.nil? ? '' : truncate(feedback.feedback))
                i.fa.fa-comment
            - else
              - if feedback
                = link_to submission_feedback_path(submission, feedback), class: 'btn btn-outline-success',"data-toggle" => "tooltip", "data-placement" => "bottom", "title" => truncate(feedback.feedback)
                  i.fa.fa-comment
              - else
                = link_to '#', class: 'btn btn-outline-primary disabled',"data-toggle" => "tooltip", "data-placement" => "bottom", "title" => "No feedback available"
                  i.fa.fa-comment
            - if submission.task.bonus?
              - if submission.user.has_locked_task? @task
                  = link_to '', data: { task_id: @task.id, user_id: submission.user.id }, class: 'btn btn-outline-primary btn-sm lock-task-btn' do
                    i.fa.fa-check
                    span.tooltiptext Korrekturbereitschaft zurückziehen
              - else
                = link_to '', data: { task_id: @task.id, user_id: submission.user.id }, class: 'btn btn-outline-primary btn-sm lock-task-btn' do
                  i.fa.fa-check
                  span.tooltiptext Zur Korrektur bereitgeben
              - if current_user.user_class == 'M'
                  = link_to '', data: { task_id: @task.id, user_id: submission.user.id }, class: 'btn btn-outline-primary btn-sm correct-task-btn' do
                    i.fa.fa-book
                    span.tooltiptext Korrektur

          - @test_cases.each do |test_case|
            td.text-center
              - test_result = submission.test_results.where(test_case_id: test_case.id).first
              - if test_result.nil?
                i.fa.fa-spinner.fa-spin.fa-2x.fa-fw
              - elsif test_result.successful
                i.fa.fa-check-circle.large-text.green
              - else
                a[data-toggle="tab" href="##{submission.id}_#{test_result.id}"]
                  div.clickable[data-toggle="modal" data-target="#failure-trace-modal"]
                    div[data-toggle="tooltip" data-placement="top" title=test_result.failure_message]
                      - if test_case.name.include?('SourceCodeTest')
                        i.fa.fa-exclamation-circle.large-text.yellow
                      - else
                        i.fa.fa-times-circle.large-text.red

    - if can? :statistics, @task
      tfoot
        tr
          td.first-column
          - num_submissions = @task.submissions.count
          - @test_cases.each do |test_case|
            td.text-center = number_to_percentage(test_case.test_results.correct.count.to_f / num_submissions * 100, precision: 0)
- if @unfinished
  div style="z-index:1001;display:flex;justify-content:center;align-items:center;width:100vw;height:100vh;position:fixed;top:0px;left:0px;background-color:black;opacity:0.9;"
    p
      i.fa.fa-spinner.fa-spin.fa-3x.fa-fw style="color:white;"
    p style="color:white;"
      | Test wird ausgeführt, dies kann einige Minuten dauern!
      br
      b Diese Seite lädt sich selbst neu, keine Angst!
    javascript:
        setTimeout(function () {
            location.reload()
        }, 10000);

#failure-trace-modal.modal.fade aria-hidden="true" aria-labelledby="myModalLabel" role="dialog" tabindex="-1"
  .modal-dialog role="document" style="width: 85%;"
    .modal-content
      .modal-header
        button.close aria-label="Close" data-dismiss="modal" type="button"
          span aria-hidden="true"  &times;
        h4#myModalLabel.modal-title Fehler Details
      .modal-body.tab-content
        - @submissions.each do |submission|
          - @test_cases.each do |test_case|
            - test_result = submission.test_results.wrong.where(test_case_id: test_case.id).first
            - unless test_result.nil?
              .tab-pane[id = "#{submission.id}_#{test_result.id}"]
                pre
                  = (test_result.failure_trace && test_result.failure_trace.strip.empty?) ? 'Keine weiteren Details vorhanden!' : test_result.failure_trace
      .modal-footer
        button.btn.btn-secondary data-dismiss="modal" type="button" style="width: 100%"  Schließen

#feedback-modal.modal.fade aria-hidden="true" aria-labelledby="feedbackModal" role="dialog" tabindex="-1"
  .modal-dialog role="document" style="width: 50%"
    .modal-content
      .modal-header
        button.close aria-label="Close" data-dismiss="modal" type="button"
          span aria-hidden="true"  &times;
        h4#myModalLabel.modal-title Feedback
      .modal-body.tab-content style="min-height: 250px"
        textarea.form-control#feedback-textarea rows="20"
      .modal-footer
        button#create-update-feedback-btn.btn.btn-secondary data-dismiss="modal" type="button" style="width: 100%"  Erstellen/Aktualisieren

app/views/tasks/statistics.html.slim
= render partial: 'statistics'