config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root to: 'application#index'

  resources :moss_matches, only: [:index, :show]
  resources :jplag_matches, only: [:show]

  resource :users, only: [] do
    get :autocomplete_display_name, :on => :collection
  end

  resources :groups do
    get :results
    get :statistics
    get :autocomplete_title, :on => :collection
    resources :groups, only: [:new]
    resources :accesses, only: [:index]
    resources :submission_tasks, only: [:new]
    resources :input_output_tasks, only: [:new]
    resources :jshell_tasks, only: [:new]
  end

  scope :groups do
    resources :attachments, only: [:create, :show]
  end

  resources :accesses, only: [:create]

  resources :accesses, only: [:destroy]

  resources :submission_tasks, except: [:new, :index] do
    get :results
    get :statistics
    get :moss_graph
    get :moss_results
    get :jplag_results
    get :download_tests
    get :download_submissions
    get :run_moss, to: 'moss_matches#run_moss'
    get :run_jplag, to: 'jplag_matches#run_jplag'
    resources :submissions, only: [:new]
  end

  resources :input_output_tasks, except: [:new, :index] do
    get :results
    get :statistics
    get :download_submissions
    resources :submissions, only: [:new]
  end

  resources :jshell_tasks, except: [:new, :index] do
    get :results
    get :statistics
    get :download_submissions
    resources :submissions, only: [:new]
  end

  resources :submissions, except: [:new] do
    get :download
    resources :feedbacks, only: [:new,:edit,:show, :update, :create]
  end

  resources :inputs, only: [:show]

  post '/lock_task', to: 'task_lock#toggle'
  post '/correct_task', to: 'task_lock#toggle_corrected'

  post 'submissions/batch_upload', to: 'submissions#batch_upload', as: 'submission_batch_upload'

  get 'errors/file_too_large'

  get 'doc', to: 'documentation#index'
  #get 'doc/*file', to: 'documentation#show'

  mount JavaSubmissionTester::Engine, at: 'java_tester'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end

app/models/moss_match.rb
class MossMatch < ApplicationRecord
  mount_uploader :submission_1_html, MossMatchHtmlUploader
  mount_uploader :submission_2_html, MossMatchHtmlUploader

  has_one :task, through: :moss_run

  belongs_to :submission_1, class_name: 'Submission', foreign_key: 'submission_1_id'
  belongs_to :submission_2, class_name: 'Submission', foreign_key: 'submission_2_id'

  belongs_to :moss_run
end

app/controllers/moss_matches_controller.rb
class MossMatchesController < SecureController
  skip_load_and_authorize_resource only: :run_moss

  def show
    @group = @moss_match.task
    @submission_1_html = IO.read @moss_match.submission_1_html.current_path
    @submission_2_html = IO.read @moss_match.submission_2_html.current_path
  end

  def run_moss
    @task = Task.find_by! id: params[:submission_task_id]

    authorize! :run, @task.moss_run
    @task.moss_run.run
  end
end

app/helpers/moss_matches_helper.rb
module MossMatchesHelper
end

app/views/moss_matches/_moss_match.slim
p
  = link_to moss_match
    = "#{moss_match.created_at}: #{moss_match.submission_1.name} #{moss_match.match_percentage_1}//#{moss_match.match_percentage_2} #{moss_match.submission_2.name}"

app/views/moss_matches/index.html.slim
= render(@moss_matches) || '<p>Bisher wurde nichts mit moss verglichen</p>'.html_safe
= will_paginate @moss_matches

app/views/moss_matches/run_moss.js.erb
$('#start-moss-button').replaceWith("<%= j(render partial: 'nav_pill', locals: {title: 'Moss starten', disabled: true}) %>")

app/views/moss_matches/show.html.slim
= render partial: 'breadcrumb', locals: {path_append: [ link_to('Moss Ergebnisse', submission_task_moss_results_path(@group)), 'Moss Vergleich']}

= content_for :title
  = "Moss Vergleich - #{@moss_match.submission_1.display_name} - #{@moss_match.submission_2.display_name}"

= content_for :main
  div.row
    div.col-lg-6
      h3 = @moss_match.submission_1.display_name
    div.col-lg-6
      h3 = @moss_match.submission_2.display_name
    div.word-wrap.moss-match-html.col-lg-6
      = raw(@submission_1_html)
    div.word-wrap.moss-match-html.col-lg-6
      = raw(@submission_2_html)
    div[style="clear: both;"]