config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root to: 'application#index'

  resources :moss_matches, only: [:index, :show]
  resources :jplag_matches, only: [:show]

  resource :users, only: [] do
    get :autocomplete_display_name, :on => :collection
  end

  resources :groups do
    get :results
    get :statistics
    get :autocomplete_title, :on => :collection
    resources :groups, only: [:new]
    resources :accesses, only: [:index]
    resources :submission_tasks, only: [:new]
    resources :input_output_tasks, only: [:new]
    resources :jshell_tasks, only: [:new]
  end

  scope :groups do
    resources :attachments, only: [:create, :show]
  end

  resources :accesses, only: [:create]

  resources :accesses, only: [:destroy]

  resources :submission_tasks, except: [:new, :index] do
    get :results
    get :statistics
    get :moss_graph
    get :moss_results
    get :jplag_results
    get :download_tests
    get :download_submissions
    get :run_moss, to: 'moss_matches#run_moss'
    get :run_jplag, to: 'jplag_matches#run_jplag'
    resources :submissions, only: [:new]
  end

  resources :input_output_tasks, except: [:new, :index] do
    get :results
    get :statistics
    get :download_submissions
    resources :submissions, only: [:new]
  end

  resources :jshell_tasks, except: [:new, :index] do
    get :results
    get :statistics
    get :download_submissions
    resources :submissions, only: [:new]
  end

  resources :submissions, except: [:new] do
    get :download
    resources :feedbacks, only: [:new,:edit,:show, :update, :create]
  end

  resources :inputs, only: [:show]

  post '/lock_task', to: 'task_lock#toggle'
  post '/correct_task', to: 'task_lock#toggle_corrected'

  post 'submissions/batch_upload', to: 'submissions#batch_upload', as: 'submission_batch_upload'

  get 'errors/file_too_large'

  get 'doc', to: 'documentation#index'
  #get 'doc/*file', to: 'documentation#show'

  mount JavaSubmissionTester::Engine, at: 'java_tester'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end

app/models/jshell_task.rb
class JshellTask < SubmissionTask
  after_initialize :init
  def init
    self.language = 'JShell'
  end
 end

app/controllers/jshell_tasks_controller.rb
# coding: utf-8
class JshellTasksController < TasksController
	def new
		#copied from SubmissionTasksController
		parent_id = params[:group_id]

		if parent_id.nil?
			flash[:error] = 'Aufgabe muss zu einer Gruppe gehören'
			redirect_back fallback_location: {controller: :groups, action: :index}
		else
			parent = Group.find_by! id: parent_id
			@jshell_task.parent = parent
			@group = parent
		end
	end

	def show
		#copied from SubmissionTasksController
		@submission = @jshell_task.submissions.find_by(user: current_user) || @jshell_task.submissions.build

		unless @submission.new_record?
			@submission.valid?
		end
	end

	def create
		@jshell_task.user = @jshell_task.parent.user

		if @jshell_task.save
			flash[:notice] = 'Aufgabe erfolgreich erstellt'

			redirect_to @jshell_task
		else
			flash[:error] = 'Konnte Aufgabe nicht speichern'
			render :new
		end
	end

	def set_task
    params[:task_id] = params[:jshell_task_id]
    @task = @jshell_task
    @group = @task
  end

	private
	def task_params
		jshell_task_params
	end

	def jshell_task_params
		params.require(:jshell_task).permit(
			:title,
			:text_content,
      :markup,
			:deadline,
			:visible,
			:parent_id,
			:test,
			:test_cache,
			:hidden_test,
			:hidden_test_cache,
			:language)
	end

end

app/helpers/jshell_tasks_helper.rb
module JshellTasksHelper
end

app/views/jshell_tasks/_form.html.slim
= render 'tasks/form',model: @jshell_task, language_selection: [@jshell_task.language] do |f|

javascript:
  updateHelpPath()

  function updateHelpPath() {
      console.error("no help available")
  }

app/views/jshell_tasks/edit.html.slim
= render partial: 'breadcrumb', locals: { path_append: "Bearbeiten" }
= content_for :main
  = render partial: 'form', object: @jshell_task

app/views/jshell_tasks/new.html.slim
= render partial: 'breadcrumb', locals: { group: @jshell_task, path_append: 'Neu JShell Aufgabe' }
= content_for :main
  = render partial: 'form', object: @jshell_task

app/views/jshell_tasks/show.html.slim
= render partial: 'breadcrumb'

- content_for :main
  h3
    - unless @jshell_task.visible
      i.fa.fa-eye-slash
    =< @jshell_task.title
    .pull-right.small
      = link_to '#bottom'
        = icon 'angle-double-down'
        | &nbsp;Abgabe
  == render_text @jshell_task

.col-lg-12#bottom
  .well
    .row
      .col-lg-12
        p
          b
            'Abgabedatum:
          = (@jshell_task.deadline.nil?) ? '--.--.----' : l(@jshell_task.deadline)
        - unless @jshell_task.deadline.nil?
          p
            b
              - if @jshell_task.deadline.future?
                'Verbleibende Zeit:
              - else
                'Abgelaufen seit:
            = distance_of_time_in_words_to_now @jshell_task.deadline
        br
    .row
      - if can? :batch_upload, @jshell_task
        .col-lg-12
          .col-xs-12.col-md-10
            = bootstrap_form_tag(url: submission_batch_upload_path(), layout: :horizontal, multipart: true, method: :post, html: {'enctype' => 'multipart/form-data'}) do
              .form-group
                = label_tag :submission_batch, 'Batch Abgabe', class: 'control-label col-sm-2'
                .col-sm-10
                  = file_field_tag :submission_batch
              = hidden_field_tag :task_id, @jshell_task.id
              .form-group
                .col-sm-10.col-sm-offset-2
                  = submit_tag 'Hochladen', class: 'btn btn-default'
              br
      .col-lg-12
        - if @jshell_task.deadline.nil? or @jshell_task.deadline.future?
          = render partial: 'submissions/form', object: @submission
        - else
          .col-md-4.text-center
          => btn_link_to "Download Tests", submission_task_download_tests_path(@task), class: 'btn-warning', target: '_blank'
          .alert.alert-danger.text-center style="margin-top:2em;"
            | Deadline abgelaufen!